# Generated by Django 3.2.6 on 2021-09-07 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('join_password', models.CharField(max_length=50, null=True)),
                ('is_join_allowed', models.BooleanField(default=True)),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yearbook.customfile')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserPerDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('bio', models.CharField(max_length=140, null=True)),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yearbook.customfile')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.profile')),
            ],
            options={
                'unique_together': {('user', 'department')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='default_user_per_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_default_department', to='yearbook.userperdepartment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yearbook.profile'),
        ),
    ]
